### ISSUE TITLE
Please add a section on how to use it in the readme

### ISSUE THREAD

**Issue by jexp** [owetterau/neo4j-websockets#1]
The current readme is a very detailed description on how the internals are set up

For a user, the "how to use it" with a few example calls and responses would demonstrate the API.

And an example project (e.g like the ones for the Neo4j Movie DB here in http://github.com/neo4j-examples/ ) would be super helpful to get started.

**Comment by owetterau** [comment]
I have created an exmaple project with how to readmes for the client and the server part.
The project can be found here: https://github.com/owetterau/neo4j-websockets-example.
The current readme links to to that project and the corresponding how to readmes.
